---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: observability
  namespace: argocd
spec:
  description: Observability stack components (Prometheus, Grafana, Loki, Vector)
  sourceRepos:
    - https://prometheus-community.github.io/helm-charts
    - https://grafana.github.io/helm-charts
    - https://helm.vector.dev
    - https://github.com/f5xc-TenantOps/f5xc-tops-mgmt-cluster.git
  destinations:
    - namespace: observability
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: "monitoring.coreos.com"
      kind: "*"
