apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terrakube
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  destination:
    name: in-cluster
    namespace: terrakube
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /status
    - group: apps
      kind: ReplicaSet
      jsonPointers:
        - /status
  sources:
    - chart: terrakube
      repoURL: https://charts.terrakube.io
      targetRevision: 3.21.0
      helm:
        valueFiles:
          - $values/terrakube/values.yml
    - repoURL: https://github.com/f5xc-TenantOps/f5xc-tops-mgmt-cluster.git
      targetRevision: HEAD
      path: terrakube
      ref: values