apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-cloud
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: 
      prune: true
  destination:
    name: in-cluster
    namespace: tfc-operator-system
  sources:
    - chart: hcp-terraform-operator
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: 2.7.1
      helm:
        valueFiles:
        - $values/tfc-operator/values.yml
    - repoURL: https://github.com/f5xc-TenantOps/f5xc-tops-mgmt-cluster.git
      targetRevision: HEAD
      path: tfc-operator
      ref: values
