---
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: tops-infra-dev
  namespace: tfc-operator-system
spec:
  organization: f5xc-tenant-ops
  terraformVersion: 1.6.2
  token:
    secretKeyRef:
      name: terraformrc
      key: token
  name: tops-infra-dev
  description: F5XC Tenant Ops Infrastructure - Development
  applyMethod: auto
  terraformVariables:
    - name: environment
      value: dev
      hcl: false
      sensitive: false
    - name: mcn_lab_token
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: tenant-tokens
          key: mcn_svc_cred
    - name: mcn_lab_token_name
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: tenant-tokens
          key: mcn_svc_cred_name
    - name: sec_lab_token
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: tenant-tokens
          key: sec_svc_cred
    - name: sec_lab_token_name
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: tenant-tokens
          key: sec_svc_cred_name
    - name: app_lab_token
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: tenant-tokens
          key: app_svc_cred
    - name: app_lab_token_name
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: tenant-tokens
          key: app_svc_cred_name
    - name: zone_id
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: ZONE_ID
    - name: acme_email
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: ACME_EMAIL
    - name: udf_principal_org_path
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: UDF_PRINCIPAL_ORG_PATH
  environmentVariables:
    - name: AWS_SECRET_ACCESS_KEY
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: AWS_SECRET_ACCESS_KEY
    - name: AWS_ACCESS_KEY_ID
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: AWS_ACCESS_KEY_ID
  versionControl:
    repository: f5xc-TenantOps/f5xc-tops-infra
    branch: dev
    oAuthTokenID: ot-mshXc8tPKM35f6Ve

