---
apiVersion: app.terraform.io/v1alpha2
kind: Workspace
metadata:
  name: shop-microservices-demo
  namespace: tfc-operator-system
spec:
  organization: f5xc-tenant-ops
  terraformVersion: 1.6.2
  token:
    secretKeyRef:
      name: terraformrc
      key: token
  name: shop-microservices-demo
  description: Demo Shop Microservices Infrastructure
  applyMethod: auto
  terraformVariables:
    - name: gcp_project_id
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: GCP_PROJECT_ID
      hcl: false
      sensitive: true
    - name: gcp_credentials
      sensitive: true
      hcl: false
      valueFrom:
        secretKeyRef:
          name: workspacesecrets
          key: GCP_CREDENTIALS
  versionControl:
    repository: f5xc-TenantOps/f5xc-tops-demo-microservices
    branch: dev
    oAuthTokenID: ot-mshXc8tPKM35f6Ve

